--1-1
SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT; 


--1-2(*)
SELECT CAPACITY "학과별 정원"
FROM TB_DEPARTMENT;

--1-3
SELECT STUDENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE SUBSTR(STUDENT_SSN , 8 , 1) = 2 
AND ABSENCE_YN  = 'Y'
AND DEPARTMENT_NAME ='국어국문학과';


--1-4
SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME  DESC;


--1-5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY BETWEEN 20 AND 30;



--1-6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


--1-7
SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


--1-8
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT 
ORDER BY CATEGORY;

--1-9
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '%전주%' 
AND SUBSTR(STUDENT_NO, 2, 1) = 2
AND ABSENCE_YN  = 'N'; 


--2-1
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT 
JOIN TB_CLASS USING(DEPARTMENT_NO)	
WHERE DEPARTMENT_NO = '002';

--2-2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE PROFESSOR_NAME NOT LIKE '___';

--2-3
SELECT PROFESSOR_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD')) /12) "나이"

FROM TB_PROFESSOR 

ORDER BY 나이 ASC;


--2-4
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) "이름"
FROM TB_PROFESSOR;


--2-5(*)
SELECT STUDENT_NO, STUDENT_NAME
FROM 



--2-6
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;


--2-7
SELECT ROUND(AVG(POINT) ,1 ) "평점"
FROM TB_GRADE
WHERE STUDENT_NO  = 'A517178';


--2-8
SELECT DEPARTMENT_NO "학과번호" , COUNT(*) "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY 학과번호 ASC;

--2-9
SELECT COUNT(*)
FROM TB_STUDENT 
WHERE COACH_PROFESSOR_NO IS NULL;

--2-10(*)
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT) , 1) "평점" 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO
ORDER BY 년도 ASC;





--2-11
SELECT DEPARTMENT_NO "학과코드명" , COUNT(*)"휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO 
ORDER BY 학과코드명 ASC;


--2-12
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT;


--2-13
SELECT SUBSTR(TERM_NO, 1, 4) "년도", SUBSTR(TERM_NO, 5, 2) "학기" ,ROUND(AVG(POINT) , 1) "평점" 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO 
ORDER BY 년도 ASC;




--3-1
SELECT STUDENT_NAME "학생이름", STUDENT_ADDRESS"주소지"
FROM TB_STUDENT
ORDER BY 학생이름 ASC;

--3-2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE ABSENCE_YN  = 'Y'
ORDER BY SUBSTR(STUDENT_SSN, 1, 6) DESC;

--3-3
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학생번호", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS  IN (SELECT STUDENT_ADDRESS 
						FROM TB_STUDENT
						WHERE STUDENT_ADDRESS LIKE '%강원도%'	OR STUDENT_ADDRESS LIKE '%경기도%')

AND SUBSTR(STUDENT_NO, 1, 1) = '9';



--3-4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY SUBSTR(PROFESSOR_SSN, 1, 6) ASC;

--3-5
SELECT STUDENT_NO , ROUND(POINT ,1) "학점"
FROM TB_GRADE 
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--3-6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;


--3-7
SELECT CLASS_NAME, DEPARTMENT_NAME	
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--3-8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_PROFESSOR USING (DEPARTMENT_NO);


--3-9
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY  = '인문사회'
ORDER BY CLASS_NAME ASC;

--3-10
SELECT STUDENT_NO, STUDENT_NAME , ROUND(AVG(POINT) ,1 )
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NO  = '059'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;


--3-11
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", COACH_PROFESSOR_NO "지도교수 이름"
FROM TB_DEPARTMENT 
JOIN TB_STUDENT USING (DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';


--3-12
SELECT 	STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NAME =  '인간관계론' AND TERM_NO LIKE '%2007%'
GROUP BY STUDENT_NAME , TERM_NO;

--3-13(*)
SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'AND PROFESSOR_NO  = (SELECT PROFESSOR_NO		
											FROM TB_PROFESSOR 
											WHERE DEPARTMENT_NO IS NULL);



--3-14(*)
SELECT STUDENT_NAME "학생이름" PROFESSOR_NAME "지도교수 이름"
FROM TB_STUDENT 
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE PROFESSOR_NAME = (SELECT PROFESSOR_NAME
						FROM TB_PROFESSOR 
						JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
						WHERE DEPARTMENT_NAME = '서반아어학과');



--3-15
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)		
FROM TB_STUDENT MAIN
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE STUDENT_NO IN (SELECT STUDENT_NO 
					FROM TB_STUDENT SUB
					WHERE ABSENCE_YN = 'Y') 

GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME;



	





























